spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop #;MVCC=TRUE  # MVCC=TRUE 잘은 모르지만 여러 요청이 한번에 들어올 때 좀 더 빨라진댄다 (권장사항)
#    url: jdbc:h2:~/jpashop
    username: sa
    data-password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      show_sql: true   # 얘는 System.out 을 이용해서 출력한댄다
      hibernate.format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
decorator:
  datasource:
    p6spy:
      multiline: false
      logging: slf4j
      enable-logging: false