spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    data-password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      show_sql: true
      hibernate.format_sql: true
logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
decorator:
  datasource:
    p6spy:
      multiline: false
      logging: slf4j
      enable-logging: false